from enum import Enum


class ReasonCode(str, Enum):
    SIGNAL_WEAK = "SIGNAL_WEAK"
    MICROSTRUCTURE_SPREAD_SHOCK = "MICROSTRUCTURE_SPREAD_SHOCK"
    MICROSTRUCTURE_DEPTH_COLLAPSE = "MICROSTRUCTURE_DEPTH_COLLAPSE"
    MICROSTRUCTURE_SLIPPAGE_ANOMALY = "MICROSTRUCTURE_SLIPPAGE_ANOMALY"
    RISK_LEVERAGE_LIMIT = "RISK_LEVERAGE_LIMIT"
    RISK_MARGIN_USAGE = "RISK_MARGIN_USAGE"
    LIQUIDATION_DISTANCE_TOO_LOW = "LIQUIDATION_DISTANCE_TOO_LOW"
    CASCADE_DETECTED = "CASCADE_DETECTED"
    ADL_PRESSURE_LONG = "ADL_PRESSURE_LONG"
    ADL_PRESSURE_SHORT = "ADL_PRESSURE_SHORT"
    POLICY_BLOCK = "POLICY_BLOCK"
    GATE_REJECT = "GATE_REJECT"
    ALLOW = "ALLOW"


class DecisionLayer(str, Enum):
    STRATEGY = "STRATEGY"
    MICROSTRUCTURE = "MICROSTRUCTURE"
    RISK_ENGINE = "RISK_ENGINE"
    LIQUIDATION = "LIQUIDATION"
    ADL = "ADL"
    POLICY = "POLICY"
    GATE = "GATE"
