from enum import Enum


class AuditEvent(str, Enum):
    SCAN_RESULT = "SCAN_RESULT"
    SCANNER_SIGNAL_GENERATED = "SCANNER_SIGNAL_GENERATED"
    RISK_RESULT = "RISK_RESULT"
    EXECUTION_INTENT = "EXECUTION_INTENT"
    ORDER_PREFLIGHT = "ORDER_PREFLIGHT"
    EXCHANGE_ORDER = "EXCHANGE_ORDER"
    SYMBOL_INTEGRITY_REJECT = "SYMBOL_INTEGRITY_REJECT"
    UNIVERSE_RESOLUTION = "UNIVERSE_RESOLUTION"
    MARKET_BIAS_RESOLUTION = "MARKET_BIAS_RESOLUTION"
    EXECUTION_MATCH_CONFIRMED = "EXECUTION_MATCH_CONFIRMED"
    EXECUTION_SUBMIT_ATTEMPT = "EXECUTION_SUBMIT_ATTEMPT"
    EXECUTION_SUBMIT_SUCCESS = "EXECUTION_SUBMIT_SUCCESS"
    EXECUTION_SUBMIT_FAILURE = "EXECUTION_SUBMIT_FAILURE"
